# Generated by Django 4.1.1 on 2023-07-16 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0002_boughtreceipt_delete_paymentreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtreceipt',
            name='seller',
        ),
        migrations.AddField(
            model_name='boughtreceipt',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
