# Generated by Django 4.1.1 on 2023-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_boughtreceipt_seller_boughtreceipt_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtreceipt',
            name='total_price',
            field=models.CharField(default=0, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
