# Generated by Django 4.1.1 on 2023-07-18 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_alter_boughtreceipt_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtreceipt',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SoldReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(editable=False, max_length=33)),
                ('quantity', models.PositiveIntegerField(default=1, editable=False)),
                ('time_sold', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('token', models.CharField(editable=False, max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
