# Generated by Django 4.1.1 on 2023-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
