# Generated by Django 4.1.1 on 2023-07-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
